[package]
name = "jackdaw_surface"
version.workspace = true
edition = "2024"
description = "Internal crate for the jackdaw editor"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jbuehler23/jackdaw"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
    "std",
    "bevy_asset",
    "bevy_pbr",
    "bevy_render",
    "bevy_image",
    "bevy_log",
    "bevy_core_pipeline",
    "bevy_post_process",
    "bevy_anti_alias",
] }
jackdaw_scene_types = { version = "0.19.0", path = "../jackdaw_scene_types", default-features = false }

[lints]
workspace = true
