[package]
name = "jackdaw_feathers"
version.workspace = true
edition = "2024"
description = "Internal crate for the jackdaw editor"
repository = "https://github.com/jbuehler23/jackdaw"
license = "MIT OR Apache-2.0"
include = ["Cargo.toml", "LICENSE*", "fonts/**/*", "src/**/*"]

[dependencies]
smol_str = { version = "0.2", default-features = false }
bevy.workspace = true
bevy_monitors.workspace = true
jackdaw_fuzzy.workspace = true
jackdaw_scene_types.workspace = true
jackdaw_widgets.workspace = true
jackdaw_commands.workspace = true
lucide-icons.workspace = true
jackdaw_localization.workspace = true

[dev-dependencies]
bevy_enhanced_input.workspace = true

[lints]
workspace = true
